plt.plot(x_val, y_val, label='Lagrange Polynomial', color='blue')
plt.scatter(x, y, color='red', label='Data Points')
plt.axvline(x=xp, color='green', linestyle='--', label=f'Interpolated x = {xp}')
plt.scatter(xp,float(int_val), color='black', label=f'Interpolated y = {float(int_val):.4f}')

plt.title('Lagrange Interpolation')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()